name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c57e98a18f801f7f8ef9c555bfb6a8dbfe3503b19f73cec2bc8a2faaf3f2b794"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
