name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f0481f71477571c7d3dcbe7ffddd260bd0e83a6eee64b20b40102626e6e828c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
