name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3939b1656e929be4925c4392ae2edd4c1a382fa7b11bb6dc318b81858048ff4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
